# Generated by Django 4.2.7 on 2023-11-20 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('children_age', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15)])),
                ('hourly_wage', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
            ],
        ),
    ]
