# Generated by Django 4.2.7 on 2023-11-12 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='children_age',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='sitter',
            name='hourly_wage',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
    ]
